# Default chat formatting
chat-format: "{world} {prefix}{group}{suffix} {dispname}&r: {message}"
# Default /me formatting
me-format: "&d * &b{dispname}&d {message}"
# Default /say formatting
say-format: "&d[Server] {message}"
# Default /ac formatting
admin-format: "&b[Admin] {dispname}:&3 {message}"
# Capitalize first word?
first-word-capital: false
# Highlight users when they are mentioned?
highlight-at-user: true
# Highlight links?
highlight-links: true
# Poof smoke on users when they are mentioned?
smoke-at-user: true
# Remove all caps messages?
remove-all-caps: true
# Percent of message that must be in caps to be make it lowercase (remove-all-caps must be true)
caps-removal-percent: 75
# Max chat radius. 0 is none. Overrides channels if greater than 0 (leave at 0 to use channel limits)
chat-radius: 0
# Allow inter-world chat? Does not override channels
interworld: true
# Use channels?
use-channels: true
# Define channels here
channels:
  # Each option in the default chat channel is required for all other channels (unless otherwise stated)
  # To join this channel: /ch default
  # To join the channel "admin" /ch admin
  default:
    # Pretty name
    name: "Default"
    # Default? There can only be one...
    default: true
    # Chat format
    chat-format: "[d] {dispname}: {message}"
    # Chat radius (0 makes for no limit - i.e. global)
    chat-radius: 0
    # Can the chat always be seen, even if you're in another channel? Overrides chat-radius. Respects interworld
    alwaysseen: true
    # Allow interworld chat in this channel? Overrides main interworld setting.
    interworld: true
    # Use a password?
    use-password: false
    # Sets the password (syntax: /ch d abc) - if use-password is false, this is optional
    password: "abc"
  admin:
    name: "Admin"
    default: false
    chat-format: "&b[Admin] {dispname}:&3 {message}"
    chat-radius: 0
    alwaysseen: false
    interworld: true
    use-password: true
    password: "supersecret"
# Set messages here. Set the message to "" to disable it entirely. Set message to "no-handle" to stop RoyalChat from handling that message
# Join messages
join-message: "&e{name} has joined."
# Quit messages
quit-message: "&e{name} has quit."
# Kick message
kick-message: "&e{name} was kicked!"
# World message
world-message: "&e{name} joined {world} from {fromworld}."
# Prefixes and Suffixes
prefixes:
  Mod: '&b'
  Admin: '&a'
suffixes:
  Mod: '&f'
  Admin: '&e'
